import { v4 as uuid } from 'uuid';
import type { CVData } from '../types';

export const defaultCVData: CVData = {
    personal: {
        name: '',
        profession: '',
        phone: '',
        email: '',
        address: '',
        dob: '',
        nationality: '',
        fatherName: '',
        motherName: '',
        religion: '',
        gender: '',
        maritalStatus: '',
        bloodGroup: '',
        height: '',
        nid: '',
        permanentAddress: '',
        website: '',
        linkedin: '',
        github: '',
    },
    careerObjective: '',
    education: [],
    experience: [
        {
            id: uuid(),
            title: 'Sales Representative',
            company: 'Pran RFL, Khagrachari',
            duration: '1 Year',
            startDate: '',
            endDate: '',
            responsibilities: [
                'Maintained customer relationships and ensured product availability in local markets.',
                'Achieved monthly sales targets through effective field visits and direct sales.',
                'Provided regular market feedback and promotional updates to management.',
            ],
        },
    ],
    computerSkills: [
        { id: uuid(), name: 'MS Excel (Data Entry, Basic Reporting)', level: 80 },
        { id: uuid(), name: 'MS Access', level: 70 },
        { id: uuid(), name: 'MS Word', level: 85 },
        { id: uuid(), name: 'PowerPoint', level: 75 },
        { id: uuid(), name: 'Internet Browsing & Email Communication', level: 90 },
        { id: uuid(), name: 'Typing (English & Bengali)', level: 85 },
    ],
    technicalSkills: [
        { id: uuid(), name: 'Communication Skills', level: 85 },
        { id: uuid(), name: 'Teamwork & Collaboration', level: 90 },
        { id: uuid(), name: 'Time Management', level: 80 },
        { id: uuid(), name: 'Problem Solving', level: 85 },
        { id: uuid(), name: 'Adaptability', level: 90 },
        { id: uuid(), name: 'Quick Learning Ability', level: 85 },
        { id: uuid(), name: 'Organizational Skills', level: 80 },
        { id: uuid(), name: 'Attention to Detail', level: 85 },
    ],
    languages: [],
    projects: [
        {
            id: uuid(),
            name: 'Sales & Inventory Management System',
            description: 'Developed a basic tracking tool for daily sales entries, product inventory records, and automated monthly sales summary reports.',
            technologies: 'MS Excel, MS Access',
            link: '',
        },
        {
            id: uuid(),
            name: 'Customer Relationship & Field Survey Tracker',
            description: 'Designed a structured database and reporting sheet to collect field feedback and log customer visits across regional markets.',
            technologies: 'MS Excel, Data Entry Tools',
            link: '',
        },
    ],
    certificates: [],
    references: [],
    awards: [],
    trainings: [],
    volunteering: [
        {
            id: uuid(),
            role: 'Volunteer Organizer',
            organization: 'Blood Donors Club, Rajshahi',
            duration: '2022 - 2023',
            description: 'Organized campus blood donation camps and coordinated emergency donor contacts for local hospital patients.',
        },
        {
            id: uuid(),
            role: 'Event Coordinator',
            organization: 'Youth Sports & Cultural Club',
            duration: '2021 - 2022',
            description: 'Assisted in managing annual sports tournaments and distributing prizes among regional participants.',
        },
    ],
    publications: [],
    hobbies: ['Playing Sports', 'Reading', 'Travelling', 'Writing'],
    declaration: '',
    sectionVisibility: {
        personal: true,
        objective: true,
        experience: true,
        education: true,
        computerSkills: true,
        technicalSkills: true,
        languages: true,
        projects: false,
        certificates: false,
        trainings: true,
        volunteering: false,
        hobbies: true,
        references: false,
        declaration: true,
    },
    photo: null,
};

export const sampleCVData: CVData = {
    personal: {
        name: 'MD. TAREKUL ISLAM',
        profession: 'Software Engineer',
        phone: '01319813281',
        email: 'tariqulislam8102020@gmail.com',
        address: 'Binna, Rajabari, Nesarabad, Pirojpur',
        dob: '10 March 2003',
        nationality: 'Bangladeshi',
        fatherName: 'Md. Tansen Ali',
        motherName: 'Mst. Shahana Begum',
        religion: 'Islam',
        gender: 'Male',
        maritalStatus: 'Unmarried',
        bloodGroup: 'B+',
        height: "5'5\"",
        nid: '5115248634',
        permanentAddress: 'Vill: Kunchi Vadra, P.O: Bamihal-6450, P.S: Singra, Dist: Natore',
        website: '',
        linkedin: '',
        github: '',
    },
    careerObjective:
        'Seeking a dynamic and challenging role where I can apply my creativity, adaptability, and skills to contribute effectively while continuously developing my professional knowledge and capabilities.',
    education: [
        {
            id: uuid(),
            degree: 'Bachelor of Arts (B.A)',
            institution: 'Rajshahi Govt. City College, Rajshahi',
            board: '',
            university: 'National University',
            group: 'English',
            session: '2021-2022',
            passingYear: '2024',
            result: '',
        },
        {
            id: uuid(),
            degree: 'Higher Secondary Certificate (HSC)',
            institution: 'Singra Dandama Pilot School & College',
            board: 'Rajshahi',
            university: '',
            group: 'Humanities',
            session: '',
            passingYear: '2020',
            result: 'GPA 4.58 (Out of 5.00)',
        },
        {
            id: uuid(),
            degree: 'Secondary School Certificate (SSC)',
            institution: 'Bamihal B.L High School',
            board: 'Rajshahi',
            university: '',
            group: 'Science',
            session: '',
            passingYear: '2018',
            result: 'GPA 3.94 (Out of 5.00)',
        },
    ],
    experience: [
        {
            id: uuid(),
            title: 'Area Sales Manager',
            company: 'Pran RFL, Dhaka',
            duration: '2 Years',
            startDate: 'Jan 2022',
            endDate: 'Present',
            responsibilities: [
                'Managed a team of 15 sales representatives across the Dhaka region.',
                'Increased regional sales by 25% within the first year of management.',
                'Developed and executed strategic marketing campaigns to boost product visibility.',
            ],
        },
        {
            id: uuid(),
            title: 'Sales Representative',
            company: 'Pran RFL, Khagrachari',
            duration: '1 Year',
            startDate: 'Jan 2021',
            endDate: 'Dec 2021',
            responsibilities: [
                'Maintained customer relationships and ensured product availability in local markets.',
                'Achieved monthly sales targets through effective field visits and direct sales.',
                'Provided regular market feedback and promotional updates to management.',
            ],
        },
        {
            id: uuid(),
            title: 'Marketing Intern',
            company: 'Local Business Group, Rajshahi',
            duration: '6 Months',
            startDate: 'Jun 2020',
            endDate: 'Dec 2020',
            responsibilities: [
                'Assisted in organizing promotional events and trade shows.',
                'Conducted market research and gathered consumer feedback.',
                'Helped maintain social media presence and online customer inquiries.',
            ],
        },
    ],
    computerSkills: [
        { id: uuid(), name: 'MS Excel (Data Entry, Basic Reporting)', level: 80 },
        { id: uuid(), name: 'MS Access', level: 70 },
        { id: uuid(), name: 'MS Word', level: 85 },
        { id: uuid(), name: 'PowerPoint', level: 75 },
        { id: uuid(), name: 'Internet Browsing & Email Communication', level: 90 },
        { id: uuid(), name: 'Typing (English & Bengali)', level: 85 },
    ],
    technicalSkills: [
        { id: uuid(), name: 'Communication Skills', level: 85 },
        { id: uuid(), name: 'Teamwork & Collaboration', level: 90 },
        { id: uuid(), name: 'Time Management', level: 80 },
        { id: uuid(), name: 'Problem Solving', level: 85 },
        { id: uuid(), name: 'Adaptability', level: 90 },
        { id: uuid(), name: 'Quick Learning Ability', level: 85 },
        { id: uuid(), name: 'Organizational Skills', level: 80 },
        { id: uuid(), name: 'Attention to Detail', level: 85 },
    ],
    languages: [
        {
            id: uuid(),
            name: 'Bengali',
            proficiency: 'Excellent',
            reading: 'Excellent',
            writing: 'Excellent',
            speaking: 'Excellent',
        },
        {
            id: uuid(),
            name: 'English',
            proficiency: 'Good',
            reading: 'Good',
            writing: 'Good',
            speaking: 'Good',
        },
    ],
    projects: [
        {
            id: uuid(),
            name: 'Sales & Inventory Management System',
            description: 'Developed a basic tracking tool for daily sales entries, product inventory records, and automated monthly sales summary reports.',
            technologies: 'MS Excel, MS Access',
            link: '',
        },
        {
            id: uuid(),
            name: 'Customer Relationship & Field Survey Tracker',
            description: 'Designed a structured database and reporting sheet to collect field feedback and log customer visits across regional markets.',
            technologies: 'MS Excel, Data Entry Tools',
            link: '',
        },
    ],
    certificates: [],
    references: [],
    awards: [],
    trainings: [],
    volunteering: [
        {
            id: uuid(),
            role: 'Volunteer Organizer',
            organization: 'Blood Donors Club, Rajshahi',
            duration: '2022 - 2023',
            description: 'Organized campus blood donation camps and coordinated emergency donor contacts for local hospital patients.',
        },
        {
            id: uuid(),
            role: 'Event Coordinator',
            organization: 'Youth Sports & Cultural Club',
            duration: '2021 - 2022',
            description: 'Assisted in managing annual sports tournaments and distributing prizes among regional participants.',
        },
    ],
    publications: [],
    hobbies: ['Playing Sports', 'Reading', 'Travelling', 'Writing'],
    declaration:
        'I hereby declare that all the information mentioned above is true and correct to the best of my knowledge and belief.',
    sectionVisibility: {
        personal: true,
        objective: true,
        experience: true,
        education: true,
        computerSkills: true,
        technicalSkills: true,
        languages: true,
        projects: false,
        certificates: false,
        trainings: true,
        volunteering: false,
        hobbies: true,
        references: false,
        declaration: true,
    },
    photo: null,
};
